#port configuration
server:
  port: 9196


spring:
  application:
    name: "CONFIG-SERVER"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Rohithsekar/Cloud-Config-Server"

#spring:
#  application:
#    name: "configserver"
#  profiles:
#    # active: native
#    active: git
#  cloud:
#    config:
#      server:
#        # native:
#        # search-locations: "classpath:/config"
#        # search-locations: "file:///Users//eazybytes//Documents//config"
#        git:
#          uri: "https://github.com/eazybytes/eazybytes-config.git"
#          default-label: main
#          timeout: 5
#          clone-on-start: true
#          force-pull: true

#eureka:
#  client:
#    register-with-eureka : true
#    fetch-registry : true
#    service-url:
#      defaultZone : http://localhost:8761/eureka/
#      instance:
#        hostname : localhost
#  instance:
#    prefer-ip-address: true


